[[Libmount]]
arch = "x86_64"
git-tree-sha1 = "86ab643e84633e540cfc38c946082cba93b6f8ca"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "5a9e729d22d4b259eef21ef51c09654c60b65eb5d145363cfa7242f46f4c5e84"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.34.0+0/Libmount.v2.34.0.x86_64-linux-gnu.tar.gz"
[[Libmount]]
arch = "i686"
git-tree-sha1 = "1034a84ba396c324ff5e14f37ad79508c589bbdc"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "7d88337a5f7afa7e7789dbfff50d00bc853039f0dd32521b8b2078b70fd5d3c8"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.34.0+0/Libmount.v2.34.0.i686-linux-musl.tar.gz"
[[Libmount]]
arch = "x86_64"
git-tree-sha1 = "2efd472734d16355167fe39c19d1d12ff950b9d9"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "9683a7abe27b809249f43efc434832c46b77197a1bbd03538f13df137eb64812"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.34.0+0/Libmount.v2.34.0.x86_64-linux-musl.tar.gz"
[[Libmount]]
arch = "aarch64"
git-tree-sha1 = "0da52f53f589befc51a5a3030e9aa4c6bcb10bbf"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "1db7ea9158502b944fa3a9b829176bbf111b84bcac0a4c00098d48eaa3c57471"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.34.0+0/Libmount.v2.34.0.aarch64-linux-musl.tar.gz"
[[Libmount]]
arch = "armv7l"
git-tree-sha1 = "dbb60b639ef8bfc9d14f63c3f4b934c6bca683a0"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "c7fee918870730e51c10fd29a196c3fb55489e3f43ccd97a99d1976983533d3a"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.34.0+0/Libmount.v2.34.0.arm-linux-musleabihf.tar.gz"
[[Libmount]]
arch = "i686"
git-tree-sha1 = "60a0ffe556cb70298bd29d7984b2c2956b83a8bd"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "94ab8235c1b451d532070a9264f94edce760d8f45312e6c7ab1e4de3f7d88142"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.34.0+0/Libmount.v2.34.0.i686-linux-gnu.tar.gz"
[[Libmount]]
arch = "armv7l"
git-tree-sha1 = "4755134567f2090db7f0ff38f1b3cde581babc0c"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "251409155397163a1cdf894f14aac81702a5807c9ea53631b6abfc7e4e1f1dee"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.34.0+0/Libmount.v2.34.0.arm-linux-gnueabihf.tar.gz"
[[Libmount]]
arch = "aarch64"
git-tree-sha1 = "934026a6d1926cf75d53b0cb09832bace7c95d95"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "93b155ae2cc1bec5f19be7a3bd091d94fc265ebef940cf24cc59d9b4cb8ccc01"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.34.0+0/Libmount.v2.34.0.aarch64-linux-gnu.tar.gz"
[[Libmount]]
arch = "powerpc64le"
git-tree-sha1 = "380785631a53a8e619a43f007aabffa583a02ddf"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "8f39b3d876df8eb79afe953b70ad045b251e7b84a7bf514c78cbbdbde0355605"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.34.0+0/Libmount.v2.34.0.powerpc64le-linux-gnu.tar.gz"
